#!/usr/bin/env python3
"""
Add imageUrl and style fields to POSA technique entries in TypeScript data files.

Requires: scripts/posa-image-mapping.json (generated by posa-extract-images.py)

Usage:
    python scripts/posa-add-fields.py

This script is idempotent — it skips entries that already have the fields.
Run it multiple times if some entries are missed (positional insertion can
shift offsets on the first pass).

POSA group -> style mapping:
    A (Group A) -> flexibility
    B (Group B) -> strength
    C (Group C) -> balance
    D (Group D) -> dynamic
"""

import json
import os
import re

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TECHNIQUE_FILES = [
    os.path.join(PROJECT_ROOT, "src", "data", "silks-techniques.ts"),
    os.path.join(PROJECT_ROOT, "src", "data", "lyra-techniques.ts"),
]

STYLE_MAP = {
    'a': 'flexibility',
    'b': 'strength',
    'c': 'balance',
    'd': 'dynamic',
}


def add_image_urls(filepath: str, mapping: dict[str, str]) -> int:
    """Add imageUrl field to POSA entries using the code -> path mapping."""
    with open(filepath) as f:
        content = f.read()

    changes = 0
    for code, image_path in mapping.items():
        id_pattern = f'id: "posa-{code}-'
        if id_pattern not in content:
            continue

        idx = content.index(id_pattern)

        # Find cues field
        cues_start = content.find('cues:', idx)
        if cues_start == -1 or cues_start > idx + 2000:
            continue

        # Find object closing brace
        close_idx = content.find('\n  },', cues_start)
        if close_idx == -1:
            close_idx = content.find('\n  }\n', cues_start)
        if close_idx == -1:
            continue

        # Skip if already has imageUrl
        section = content[idx:close_idx]
        if 'imageUrl:' in section:
            continue

        # Find end of cues (single-line or multi-line)
        cues_line_end = content.find('\n', cues_start)
        cues_line = content[cues_start:cues_line_end]

        if ']' in cues_line:
            insert_pos = cues_line_end
        else:
            close_bracket = content.find('],', cues_start)
            if close_bracket == -1 or close_bracket > close_idx + 200:
                continue
            insert_pos = content.find('\n', close_bracket)

        content = content[:insert_pos] + f'\n    imageUrl: "{image_path}",' + content[insert_pos:]
        changes += 1

    with open(filepath, 'w') as f:
        f.write(content)
    return changes


def add_styles(filepath: str) -> int:
    """Add style field to POSA entries based on their group code letter."""
    with open(filepath) as f:
        content = f.read()

    changes = 0
    pattern = re.compile(r'id: "posa-[sh]([abcd])\d{3}-')

    for match in pattern.finditer(content):
        group_letter = match.group(1)
        style = STYLE_MAP[group_letter]
        id_pos = match.start()

        region_end = min(id_pos + 2000, len(content))
        region = content[id_pos:region_end]

        # Skip if already has style
        first_obj_boundary = region.find('},{')
        check_region = region[:first_obj_boundary] if first_obj_boundary != -1 else region
        if 'style:' in check_region:
            continue

        # Insert after imageUrl line
        img_match = re.search(r'imageUrl: "[^"]*",', region)
        if img_match:
            insert_after = id_pos + img_match.end()
            content = content[:insert_after] + f'\n    style: "{style}",' + content[insert_after:]
            changes += 1

    with open(filepath, 'w') as f:
        f.write(content)
    return changes


def main():
    mapping_path = os.path.join(PROJECT_ROOT, "scripts", "posa-image-mapping.json")

    if os.path.exists(mapping_path):
        with open(mapping_path) as f:
            mapping = json.load(f)

        print("Adding imageUrl fields...")
        for filepath in TECHNIQUE_FILES:
            name = os.path.basename(filepath)
            # May need multiple passes due to offset shifts
            total = 0
            for _ in range(5):
                n = add_image_urls(filepath, mapping)
                total += n
                if n == 0:
                    break
            print(f"  {name}: added {total} imageUrl entries")
    else:
        print(f"No mapping file at {mapping_path}, skipping imageUrl.")
        print("Run posa-extract-images.py first to generate it.")

    print("Adding style fields...")
    for filepath in TECHNIQUE_FILES:
        name = os.path.basename(filepath)
        total = 0
        for _ in range(5):
            n = add_styles(filepath)
            total += n
            if n == 0:
                break
        print(f"  {name}: added {total} style entries")


if __name__ == "__main__":
    main()
